/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#ffdadb",
        "on-secondary-container": "#00311f",
        "on-primary-fixed-variant": "#004395",
        "on-secondary-fixed": "#002113",
        "inverse-on-surface": "#283044",
        "inverse-primary": "#005ac2",
        "surface-variant": "#2d3449",
        "secondary": "#4edea3",
        "on-secondary": "#003824",
        "inverse-surface": "#dae2fd",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "surface-dim": "#0A0A0A",
        "on-tertiary-container": "#ee3a5a",
        "tertiary-fixed-dim": "#ffb2b7",
        "outline": "#383838",
        "primary-fixed-dim": "#adc6ff",
        "primary-fixed": "#d8e2ff",
        "on-surface": "#dae2fd",
        "on-tertiary-fixed-variant": "#92002a",
        "surface-container-highest": "#2d3449",
        "secondary-fixed": "#6ffbbe",
        "surface-container": "#171f33",
        "on-secondary-fixed-variant": "#005236",
        "surface-container-low": "#131b2e",
        "outline-variant": "#383838",
        "surface-container-lowest": "#0A0A0A",
        "on-tertiary": "#67001b",
        "surface-bright": "#31394d",
        "surface-container-high": "#161616",
        "on-error": "#690005",
        "tertiary-container": "#39000b",
        "on-background": "#dae2fd",
        "tertiary": "#ffb2b7",
        "primary": "#adc6ff",
        "on-error-container": "#ffdad6",
        "primary-container": "#00163a",
        "on-primary": "#002e6a",
        "surface": "#0A0A0A",
        "secondary-container": "#00a572",
        "on-surface-variant": "#c6c6cd",
        "secondary-fixed-dim": "#4edea3",
        "on-primary-container": "#357df1",
        "on-primary-fixed": "#001a42",
        "background": "#0A0A0A",
        "surface-tint": "#adc6ff",
        "on-tertiary-fixed": "#40000d"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"],
        "sans": ["Inter", "sans-serif"],
      },
      borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
    },
  },
  plugins: [],
}
